name: Build

on:
  workflow_dispatch: {}
  push: {}

jobs:
  build_linux:
    name: Linux build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make neworigins_v3
    - uses: actions/upload-artifact@v2
      with:
        name: neworigins_v3_linux
        path: neworigins_v3/neworigins_v3
  build_windows:
    name: Windows build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: make neworigins_v3
    - uses: actions/upload-artifact@v2
      with:
        name: neworigins_v3_windows
        path: neworigins_v3/neworigins_v3.exe
